version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=true
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - techpulse-network

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api
    networks:
      - techpulse-network

networks:
  techpulse-network:
    driver: bridge
