# Render Blueprint for TexhPulze Backend
# This file configures the Render deployment for the TexhPulze backend API

services:
  # Backend API Service
  - type: web
    name: texhpulze-api
    env: node
    plan: starter
    buildCommand: |
      cd backend && 
      npm ci && 
      npm run build && 
      npm run typeorm:migrate
    startCommand: cd backend && npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: texhpulze-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://texhpulze.com
      - key: API_BASE_URL
        value: https://texhpulze-api.onrender.com
    autoDeploy: true
    branch: main
    rootDir: .

  # Background Worker Service
  - type: worker
    name: texhpulze-worker
    env: node
    plan: starter
    buildCommand: |
      cd backend && 
      npm ci && 
      npm run build
    startCommand: cd backend && npm run worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: texhpulze-db
          property: connectionString
      - key: JWT_SECRET
        fromService:
          type: web
          name: texhpulze-api
          envVarKey: JWT_SECRET
      - key: OPENAI_API_KEY
        fromService:
          type: web
          name: texhpulze-api
          envVarKey: OPENAI_API_KEY
      - key: REDIS_URL
        fromService:
          type: redis
          name: texhpulze-redis
          property: connectionString
    autoDeploy: true
    branch: main
    rootDir: .

databases:
  # PostgreSQL Database
  - name: texhpulze-db
    databaseName: texhpulze_production
    user: texhpulze_user
    plan: starter

  # Redis Cache
  - name: texhpulze-redis
    plan: starter

# Static Site for Frontend (optional)
staticSites:
  - name: texhpulze-frontend
    buildCommand: |
      cd frontend && 
      npm ci && 
      npm run build
    publishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://texhpulze-api.onrender.com
    autoDeploy: true
    branch: main
    rootDir: .
