name: Mobile EAS Build

on:
  push:
    branches: [main]
    paths:
      - "TexhPulzeMobile/**"
      - ".github/workflows/mobile-eas.yml"
  pull_request:
    branches: [main]
    paths:
      - "TexhPulzeMobile/**"
      - ".github/workflows/mobile-eas.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: TexhPulzeMobile/package-lock.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./TexhPulzeMobile
        run: npm ci

      - name: Run tests
        working-directory: ./TexhPulzeMobile
        run: |
          npm run test:components
          npm run test:mobile

      - name: Lint code
        working-directory: ./TexhPulzeMobile
        run: npm run lint || echo "Linting not configured, skipping..."

  build-android-preview:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: TexhPulzeMobile/package-lock.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./TexhPulzeMobile
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-token: ${{ secrets.EAS_TOKEN }}

      - name: Build Android preview
        working-directory: ./TexhPulzeMobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          eas build --platform android --profile preview --non-interactive

      - name: Download build artifacts
        working-directory: ./TexhPulzeMobile
        run: |
          # Download the built APK for distribution
          eas build:list --platform android --limit 1 --json > build-info.json
          BUILD_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
          if [ "$BUILD_URL" != "null" ]; then
            curl -L -o texhpulze-preview.apk "$BUILD_URL"
            echo "Build downloaded: texhpulze-preview.apk"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-preview-build-${{ github.sha }}
          path: TexhPulzeMobile/texhpulze-preview.apk
          retention-days: 30

  build-ios-preview:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: TexhPulzeMobile/package-lock.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./TexhPulzeMobile
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-token: ${{ secrets.EAS_TOKEN }}

      - name: Build iOS preview
        working-directory: ./TexhPulzeMobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          eas build --platform ios --profile preview --non-interactive

      - name: Download build artifacts
        working-directory: ./TexhPulzeMobile
        run: |
          # Download the built IPA for distribution
          eas build:list --platform ios --limit 1 --json > build-info.json
          BUILD_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
          if [ "$BUILD_URL" != "null" ]; then
            curl -L -o texhpulze-preview.ipa "$BUILD_URL"
            echo "Build downloaded: texhpulze-preview.ipa"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-preview-build-${{ github.sha }}
          path: TexhPulzeMobile/texhpulze-preview.ipa
          retention-days: 30

  build-production:
    runs-on: ubuntu-latest
    needs: [build-android-preview]
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: TexhPulzeMobile/package-lock.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./TexhPulzeMobile
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-token: ${{ secrets.EAS_TOKEN }}

      - name: Build production Android
        working-directory: ./TexhPulzeMobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          eas build --platform android --profile production --non-interactive

      - name: Submit to Google Play (if configured)
        working-directory: ./TexhPulzeMobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          # Only submit if Google Play credentials are configured
          if [ -n "$GOOGLE_SERVICE_ACCOUNT_KEY" ]; then
            eas submit --platform android --latest --non-interactive
          else
            echo "Google Play credentials not configured, skipping submission"
          fi

  notify:
    runs-on: ubuntu-latest
    needs: [build-android-preview, build-ios-preview, build-production]
    if: always()

    steps:
      - name: Notify build status
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: "#mobile-builds"
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        if: always() && env.SLACK_WEBHOOK != ''
